version: '3.8'

services:
  php:
    build:
      context: ./php  
    ports:
      - "8080:80"    
    volumes:
      - ./php:/var/www/html  
    depends_on:
      - db 

  db:
    image: mysql:5.7       
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306" 
  
volumes:
  db_data:
    driver: local 
